// Tools configuration for scalability and easy maintenance
export const TOOLS_CONFIG = {
  studentTools: [
    {
      id: 'study-plan',
      name: 'AI Study Planner',
      icon: '📅',
      description: 'Get personalized study plans generated by AI',
      category: 'student',
      modalTitle: '🎯 AI Study Planner',
      buttonText: 'Create Study Plan',
      buttonColor: 'bg-green-600 hover:bg-green-700'
    },
    {
      id: 'flashcards',
      name: 'Flash Card Generator',
      icon: '🗂️',
      description: 'Generate concept-based MCQs using FAISS-indexed chunks and vector search technology',
      category: 'student',
      modalTitle: '🗂️ AI Flash Card Generator',
      buttonText: 'Generate Cards',
      buttonColor: 'bg-purple-600 hover:bg-purple-700'
    },
    {
      id: 'summarize',
      name: 'Note Summarizer',
      icon: '📝',
      description: 'AI-powered summarization of your study notes',
      category: 'student',
      modalTitle: 'AI Note Summarizer',
      buttonText: 'Summarize Notes',
      buttonColor: 'bg-green-600 hover:bg-green-700'
    }
  ],
  teacherTools: [
    {
      id: 'quiz-generator',
      name: 'AI Quiz Generator',
      icon: '📊',
      description: 'Generate custom quizzes and assessments using FAISS-indexed chunks and vector search technology',
      category: 'teacher',
      modalTitle: '🤖 AI Quiz Generator with FAISS Vector Search',
      buttonText: 'Generate Quiz',
      buttonColor: 'bg-purple-600 hover:bg-purple-700'
    },
    {
      id: 'lesson-planner',
      name: 'AI Lesson Planner',
      icon: '📚',
      description: 'AI-assisted lesson plan creation and resource management',
      category: 'teacher',
      modalTitle: '📚 AI Lesson Planner',
      buttonText: 'Plan Lessons',
      buttonColor: 'bg-purple-600 hover:bg-purple-700'
    },
    {
      id: 'progress-tracker',
      name: 'Progress Tracker',
      icon: '📈',
      description: 'Monitor student progress and generate reports',
      category: 'teacher',
      modalTitle: '📈 AI Progress Tracker',
      buttonText: 'View Analytics',
      buttonColor: 'bg-purple-600 hover:bg-purple-700',
      comingSoon: true
    }
  ],
  quickActions: [
    {
      id: 'study-guide',
      name: 'Study Guide',
      icon: '📖',
      comingSoon: true
    },
    {
      id: 'practice-tests',
      name: 'Practice Tests',
      icon: '🎯',
      comingSoon: true
    },
    {
      id: 'assignments',
      name: 'Assignments',
      icon: '📋',
      comingSoon: true
    },
    {
      id: 'qa-forum',
      name: 'Q&A Forum',
      icon: '💬',
      comingSoon: true
    }
  ],
  comingSoonFeatures: [
    'Virtual Classroom Integration',
    'Collaborative Study Groups',
    'AI Tutoring Sessions',
    'Advanced Analytics Dashboard'
  ]
};

export const getToolById = (id) => {
  const allTools = [
    ...TOOLS_CONFIG.studentTools,
    ...TOOLS_CONFIG.teacherTools,
    ...TOOLS_CONFIG.quickActions
  ];
  return allTools.find(tool => tool.id === id);
};
